openapi: 3.1.0
info:
  title: REST Shop Demo
  version: v1

servers:
  - url: http://localhost:8080

paths:
  /products:
    get:
      summary: Get all products
      tags:
        - Products
      operationId: getAllProducts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Save product
      tags:
        - Products
      operationId: saveProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /products/{id}:
    get:
      summary: Get product by ID
      tags:
        - Products
      operationId: getProductById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update product by ID
      tags:
        - Products
      operationId: updateProduct
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete product by ID
      tags:
        - Products
      operationId: deleteProduct
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /orders:
    get:
      summary: Get all orders
      tags:
        - Orders
      operationId: getAllOrders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
    post:
      summary: Save order
      tags:
        - Orders
      operationId: saveOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrder'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /orders/{id}:
    get:
      summary: Get order by ID
      tags:
        - Orders
      operationId: getOrderById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /orders/{id}/pay:
    put:
      summary: Pay order
      tags:
        - Orders
      operationId: payOrder
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /orders/{id}/cancel:
    put:
      summary: Cancel order
      tags:
        - Orders
      operationId: cancelOrder
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 100
          minLength: 0
          pattern: '^[\p{L}\p{S}\p{N}\p{P}\x20]*$'
        unit:
          $ref: '#/components/schemas/QuantityUnit'
        price:
          type: number
        stock:
          type: number
      required:
        - name
        - price
        - stock
        - unit

    CreateOrder:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
          minItems: 1
      required:
        - items

    OrderItem:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/OrderProduct'
        amount:
          type: number
      required:
        - amount
        - product

    OrderProduct:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      required:
        - id

    OrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        state:
          $ref: '#/components/schemas/OrderState'
        price:
          type: number
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        createdOn:
          type: string
          format: date-time

    QuantityUnit:
      type: string
      enum:
        - PIECE
        - GRAM
        - LITER
        - METER

    OrderState:
      type: string
      enum:
        - NEW
        - PAID
        - CANCELLED

    ErrorResponse:
      type: object
      properties:
        errorCode:
          $ref: '#/components/schemas/ErrorResponseCode'
        errorDetails:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'

    ErrorDetail:
      type: object
      properties:
        entityId:
          type: string
          format: uuid
        field:
          type: string
        message:
          type: string
        values:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetailValue'

    ErrorDetailValue:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ErrorDetailValueType'
        value:
          type: string

    ErrorResponseCode:
      type: string
      enum:
        - ENTITY_NOT_FOUND
        - REQUEST_VALIDATION_ERROR
        - PRODUCT_STOCK_SHORTAGE
        - ILLEGAL_ORDER_STATE
        - ILLEGAL_AMOUNT_SCALE

    ErrorDetailValueType:
      type: string
      enum:
        - MISSING_AMOUNT
        - CURRENT_STATE
        - ALLOWED_STATE
        - VALIDATION_CODE
