openapi: 3.1.0
info:
  title: REST Shop Demo
  version: v1

servers:
  - url: http://localhost:8080

paths:
  /products:
    get:
      summary: Get all products
      tags:
        - products
      operationId: getAllProducts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
    post:
      summary: Save product
      tags:
        - products
      operationId: saveProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
  /products/{id}:
    get:
      summary: Get product by ID
      tags:
        - products
      operationId: getProductById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
    put:
      summary: Update product by ID
      tags:
        - products
      operationId: updateProduct
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
    delete:
      summary: Delete product by ID
      tags:
        - products
      operationId: deleteProduct
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /orders:
    get:
      summary: Get all orders
      tags:
        - orders
      operationId: getAllOrders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponseDto'
    post:
      summary: Save order
      tags:
        - orders
      operationId: saveOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
  /orders/{id}:
    get:
      summary: Get order by ID
      tags:
        - orders
      operationId: getOrderById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDto'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
  /orders/{id}/pay:
    put:
      summary: Pay order
      tags:
        - orders
      operationId: payOrder
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
  /orders/{id}/cancel:
    put:
      summary: Cancel order
      tags:
        - orders
      operationId: cancelOrder
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    ProductDto:
      type: object
      x-class-extra-annotation: '@cz.kromer.restshopdemo.dto.validation.ProductStockMaxScale'
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 100
          pattern: '^[\p{L}\p{S}\p{N}\p{P}\x20]*$'
          x-field-extra-annotation: '@NotBlank'
        unit:
          $ref: '#/components/schemas/QuantityUnit'
        price:
          type: number
          minimum: 0
          x-field-extra-annotation: '@Digits(integer = 17, fraction = 2)'
        stock:
          type: number
          minimum: 0
          x-field-extra-annotation: '@Digits(integer = 16, fraction = 3)'
      required: [ name, price, stock, unit ]
      example:
        id: 00000000-0000-0000-0000-000000000000
        name: Milk 1 l
        unit: PIECE
        price: 28.5
        stock: 20

    CreateOrderDto:
      type: object
      properties:
        items:
          type: array
          minItems: 1
          x-field-extra-annotation:
            - '@NotEmpty'
            - '@cz.kromer.restshopdemo.dto.validation.UniqueOrderProduct'
            - '@cz.kromer.restshopdemo.dto.validation.NotNullItems'
          items:
            $ref: '#/components/schemas/OrderItemDto'
      required: [ items ]

    OrderItemDto:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/OrderProductDto'
        amount:
          type: number
          exclusiveMinimum: 0
          x-field-extra-annotation:
            - '@Positive'
            - '@Digits(integer = 16, fraction = 3)'
      required: [ amount, product ]

    OrderProductDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      required: [ id ]

    OrderResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        state:
          $ref: '#/components/schemas/OrderState'
        price:
          type: number
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemDto'
        createdOn:
          type: string
          format: date-time

    QuantityUnit:
      type: string
      enum:
        - PIECE
        - GRAM
        - LITER
        - METER

    OrderState:
      type: string
      enum:
        - NEW
        - PAID
        - CANCELLED

    ErrorResponseDto:
      type: object
      properties:
        errorCode:
          $ref: '#/components/schemas/ErrorResponseCode'
        errorDetails:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetailDto'

    ErrorDetailDto:
      type: object
      properties:
        entityId:
          type: string
          format: uuid
        field:
          type: string
        message:
          type: string
        values:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetailValueDto'

    ErrorDetailValueDto:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ErrorDetailValueType'
        value:
          type: string

    ErrorResponseCode:
      type: string
      enum:
        - ENTITY_NOT_FOUND
        - REQUEST_VALIDATION_ERROR
        - PRODUCT_STOCK_SHORTAGE
        - ILLEGAL_ORDER_STATE
        - ILLEGAL_AMOUNT_SCALE

    ErrorDetailValueType:
      type: string
      enum:
        - MISSING_AMOUNT
        - CURRENT_STATE
        - ALLOWED_STATE
        - VALIDATION_CODE
