application:
  scheduling:
    order-cancellation:
      cron: 0 * * * * *
      new-order-retention-duration: PT30M

server:
  servlet:
    context-path: /rest-shop-demo

spring:
  web:
    locale: en
  datasource:
    url: jdbc:h2:mem:demo
  jpa:
    open-in-view: false
    show-sql: false
    hibernate.ddl-auto: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true